baseURL = 'https://mikedecr.computer'
languageCode = 'en-us'
title = ':: mikedecr.computer'
theme = 'hugo-theme-re-terminal'

pagination.pagerSize = 10  # ACTUALLY controls num. blog entries per page.

[params]
themeColor = "kanagawa"
contentTypeName = "posts"
showMenuItems = 5

[languages]
[languages.en.params]
    readMore = "Read More"
    menuMore = "Show More"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    [languages.en.params.logo]
        logoText = "mikedecr[.]computer"

# nav menu
[languages.en.menu]
[[languages.en.menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
[[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/"

# tell md -> html markup to ignore math-related chars
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]


# --- for quarto ---
# hugo shouldn't touch these
# [module]
# [[module.mounts]]
# "source" = "content"
# "target" = "content"
[module]
[[module.mounts]]
source = "content"
target = "content"
excludeFiles = [
    "blog/**/*.qmd",
    "blog/**/*.ipynb",
    "blog/**/*.py",
    "blog/**/pixi.toml",
    "blog/**/pixi.lock"
]

# hugo should allow raw HTML in .md
[markup.goldmark.renderer]
unsafe= true
