baseURL = 'https://mikedecr.netlify.app'
languageCode = 'en-us'
title = ':: Michael DeCrescenzo'
theme = 'hugo-theme-re-terminal'

[params]
themeColor = "orange"
contentTypeName = "posts"

[languages.en.params]
    [languages.en.params.logo]
        logoText = "Michael DeCrescenzo"
# nav menu
[languages.en.menu]
[[languages.en.menu.main]]
[[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
