[project]
name = "mikedecr-website"
description = "Personal website"
version = "0.1.0"
# author = "Michael DeCrescenzo"
# Repository = "https://github.com/mikedecr/site-hugo"
# Issues = "https://github.com/mikedecr/site-hugo/issues"

[project.scripts]
mkd = "scripts.builder.main:app"

[mkd.links]
src.blog = [
    "submodules/blog-monorepo/causal-bayes-3-pillars",
    "submodules/blog-monorepo/nonflat-priors"
]
